package com.kraken.tools.environment;

import com.kraken.tools.obfuscation.ExcludeFromObfuscation;

@ExcludeFromObfuscation
public enum KrakenEnvironmentKeys {
  JAVA_OPTS,
  KRAKEN_GATLING_LOGS_INFO,
  KRAKEN_GATLING_LOGS_DEBUG,

  KRAKEN_TASKID,
  KRAKEN_TASKTYPE,
  KRAKEN_HOSTID,
  KRAKEN_DESCRIPTION,
  KRAKEN_CONTAINER_LABEL,
  KRAKEN_EXPECTED_COUNT,
  KRAKEN_APPLICATION_ID,

  KRAKEN_VERSION,
  KRAKEN_INFLUXDB_URL,
  KRAKEN_INFLUXDB_DATABASE,
  KRAKEN_INFLUXDB_USER,
  KRAKEN_INFLUXDB_PASSWORD,
  KRAKEN_ANALYSIS_URL,
  KRAKEN_RUNTIME_URL,
  KRAKEN_STORAGE_URL,

  KRAKEN_GATLING_JAVAOPTS,
  KRAKEN_GATLING_SIMULATION_NAME,
  KRAKEN_GATLING_SIMULATION_CLASSNAME,
  KRAKEN_GATLING_SIMULATION_PACKAGENAME,
  KRAKEN_GATLING_HARPATH_REMOTE,
  KRAKEN_GATLING_CONTAINER_NAME,
  KRAKEN_GATLING_CONTAINER_LABEL,
  KRAKEN_GATLING_SIDEKICK_NAME,
  KRAKEN_GATLING_SIDEKICK_LABEL
}
