{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.frontend.project.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "name" . }}-project-ui
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ template "name" . }}-project-ui
              servicePort: {{ .Values.frontend.project.service.port }}
            path: {{ .Values.frontend.project.ingress.path }}
      host: {{ .Values.ingress.host }}
{{- end }}