package com.octoperf.kraken.tools.environment;

import com.octoperf.kraken.tools.obfuscation.ExcludeFromObfuscation;

@ExcludeFromObfuscation
public enum KrakenEnvironmentKeys {
  JAVA_OPTS,
  KRAKEN_GATLING_LOGS_INFO,
  KRAKEN_GATLING_LOGS_DEBUG,

  KRAKEN_TASK_ID,
  KRAKEN_TASK_TYPE,
  KRAKEN_HOST_ID,
  KRAKEN_DESCRIPTION,
  KRAKEN_CONTAINER_LABEL,
  KRAKEN_EXPECTED_COUNT,
  KRAKEN_APPLICATION_ID,
  KRAKEN_PROJECT_ID,
  KRAKEN_USER_ID,

  KRAKEN_VERSION,
  KRAKEN_INFLUXDB_URL,
  KRAKEN_INFLUXDB_DATABASE,
  KRAKEN_INFLUXDB_USER,
  KRAKEN_INFLUXDB_PASSWORD,
  KRAKEN_BACKEND_URL,
  KRAKEN_HOSTNAME,
  KRAKEN_IP,

  KRAKEN_GATLING_JAVA_OPTS,
  KRAKEN_GATLING_SIMULATION_NAME,
  KRAKEN_GATLING_SIMULATION_CLASS_NAME,
  KRAKEN_GATLING_SIMULATION_PACKAGE_NAME,
  KRAKEN_GATLING_HAR_PATH_REMOTE,
  KRAKEN_GATLING_CONTAINER_NAME,
  KRAKEN_GATLING_CONTAINER_LABEL,
  KRAKEN_GATLING_SIDEKICK_NAME,
  KRAKEN_GATLING_SIDEKICK_LABEL,
  KRAKEN_GATLING_SCENARIO_CUSTOM_SETUP,
  KRAKEN_GATLING_SCENARIO_CONCURRENT_USERS,
  KRAKEN_GATLING_SCENARIO_RAMP_UP_DURATION,
  KRAKEN_GATLING_SCENARIO_PEAK_DURATION,
  HOME,

  KRAKEN_SECURITY_URL,
  KRAKEN_SECURITY_REALM,
  KRAKEN_SECURITY_WEB_ID,
  KRAKEN_SECURITY_CONTAINER_ID,
  KRAKEN_SECURITY_CONTAINER_SECRET,
  KRAKEN_SECURITY_ACCESS_TOKEN,
  KRAKEN_SECURITY_REFRESH_TOKEN,
  KRAKEN_SECURITY_EXPIRES_IN,
  KRAKEN_SECURITY_REFRESH_EXPIRES_IN,

  GIT_SSH_COMMAND,
}
