package com.kraken.tools.environment;

public interface KrakenEnvironmentKeys {

  String KRAKEN_GATLING_RESULT_INFO_LOG = "KRAKEN_GATLING_RESULT_INFO_LOG";
  String KRAKEN_GATLING_RESULT_DEBUG_LOG = "KRAKEN_GATLING_RESULT_DEBUG_LOG";
  String KRAKEN_TEST_ID = "KRAKEN_TEST_ID";
  String KRAKEN_INJECTOR = "KRAKEN_INJECTOR";

  String JAVA_OPTS = "JAVA_OPTS";
  String KRAKEN_TASK_ID = "KRAKEN_TASK_ID";
  String KRAKEN_TASK_TYPE = "KRAKEN_TASK_TYPE";
  String KRAKEN_HOST_ID = "KRAKEN_HOST_ID";
  String KRAKEN_DESCRIPTION = "KRAKEN_DESCRIPTION";
  String KRAKEN_CONTAINER_LABEL = "KRAKEN_CONTAINER_LABEL";
  String KRAKEN_EXPECTED_COUNT = "KRAKEN_EXPECTED_COUNT";
  String KRAKEN_APPLICATION_ID = "KRAKEN_APPLICATION_ID";

  String KRAKEN_VERSION = "KRAKEN_VERSION";
  String KRAKEN_INFLUXDB_URL = "KRAKEN_INFLUXDB_URL";
  String KRAKEN_INFLUXDB_DATABASE = "KRAKEN_INFLUXDB_DATABASE";
  String KRAKEN_INFLUXDB_USER = "KRAKEN_INFLUXDB_USER";
  String KRAKEN_INFLUXDB_PASSWORD = "KRAKEN_INFLUXDB_PASSWORD";
  String KRAKEN_ANALYSIS_URL = "KRAKEN_ANALYSIS_URL";
  String KRAKEN_RUNTIME_URL = "KRAKEN_RUNTIME_URL";
  String KRAKEN_STORAGE_URL = "KRAKEN_STORAGE_URL";

  String KRAKEN_GATLING_JAVA_OPTS = "KRAKEN_GATLING_JAVA_OPTS";
  String KRAKEN_GATLING_SIMULATION = "KRAKEN_GATLING_SIMULATION";
  String KRAKEN_GATLING_SIMULATION_CLASS = "KRAKEN_GATLING_SIMULATION_CLASS";
  String KRAKEN_GATLING_SIMULATION_PACKAGE = "KRAKEN_GATLING_SIMULATION_PACKAGE";
  String KRAKEN_GATLING_HAR_PATH_REMOTE = "KRAKEN_GATLING_HAR_PATH_REMOTE";
  String KRAKEN_GATLING_CONTAINER_NAME = "KRAKEN_GATLING_CONTAINER_NAME";
  String KRAKEN_GATLING_CONTAINER_LABEL = "KRAKEN_GATLING_CONTAINER_LABEL";
  String KRAKEN_GATLING_SIDEKICK_NAME = "KRAKEN_GATLING_SIDEKICK_NAME";
  String KRAKEN_GATLING_SIDEKICK_LABEL = "KRAKEN_GATLING_SIDEKICK_LABEL";
}
