package com.kraken.tools.environment;

public interface KrakenEnvironmentKeys {
  String JAVA_OPTS = "JAVA_OPTS";

  String KRAKEN_GATLING_LOGS_INFO = "KRAKEN_GATLING_LOGS_INFO";
  String KRAKEN_GATLING_LOGS_DEBUG = "KRAKEN_GATLING_LOGS_DEBUG";

  String KRAKEN_TASKID = "KRAKEN_TASKID";
  String KRAKEN_TASKTYPE = "KRAKEN_TASKTYPE";
  String KRAKEN_HOSTID = "KRAKEN_HOSTID";
  String KRAKEN_DESCRIPTION = "KRAKEN_DESCRIPTION";
  String KRAKEN_CONTAINER_LABEL = "KRAKEN_CONTAINER_LABEL";
  String KRAKEN_EXPECTED_COUNT = "KRAKEN_EXPECTED_COUNT";
  String KRAKEN_APPLICATION_ID = "KRAKEN_APPLICATION_ID";

  String KRAKEN_VERSION = "KRAKEN_VERSION";
  String KRAKEN_INFLUXDB_URL = "KRAKEN_INFLUXDB_URL";
  String KRAKEN_INFLUXDB_DATABASE = "KRAKEN_INFLUXDB_DATABASE";
  String KRAKEN_INFLUXDB_USER = "KRAKEN_INFLUXDB_USER";
  String KRAKEN_INFLUXDB_PASSWORD = "KRAKEN_INFLUXDB_PASSWORD";
  String KRAKEN_ANALYSIS_URL = "KRAKEN_ANALYSIS_URL";
  String KRAKEN_RUNTIME_URL = "KRAKEN_RUNTIME_URL";
  String KRAKEN_STORAGE_URL = "KRAKEN_STORAGE_URL";

  String KRAKEN_GATLING_JAVAOPTS = "KRAKEN_GATLING_JAVAOPTS";
  String KRAKEN_GATLING_SIMULATION_NAME = "KRAKEN_GATLING_SIMULATION_NAME";
  String KRAKEN_GATLING_SIMULATION_CLASSNAME = "KRAKEN_GATLING_SIMULATION_CLASSNAME";
  String KRAKEN_GATLING_SIMULATION_PACKAGENAME = "KRAKEN_GATLING_SIMULATION_PACKAGENAME";
  String KRAKEN_GATLING_HARPATH_REMOTE = "KRAKEN_GATLING_HARPATH_REMOTE";
  String KRAKEN_GATLING_CONTAINER_NAME = "KRAKEN_GATLING_CONTAINER_NAME";
  String KRAKEN_GATLING_CONTAINER_LABEL = "KRAKEN_GATLING_CONTAINER_LABEL";
  String KRAKEN_GATLING_SIDEKICK_NAME = "KRAKEN_GATLING_SIDEKICK_NAME";
  String KRAKEN_GATLING_SIDEKICK_LABEL = "KRAKEN_GATLING_SIDEKICK_LABEL";
}
