version: '3.5'

networks:
  kraken:
    name: kraken
    external: true

services:
  kraken-gatling-debugger:
    image: "octoperf/kraken-gatling-runner:${KRAKEN_VERSION}"
    container_name: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_CONTAINER_NAME}_STARTING"
    networks:
      - kraken
    deploy:
      resources:
        limits:
          cpus: "${KRAKEN_GATLING_CPU_LIMIT}"
          memory: "${KRAKEN_GATLING_MEMORY_LIMIT}"
        reservations:
          cpus: "${KRAKEN_GATLING_CPU_REQUEST}"
          memory: "${KRAKEN_GATLING_MEMORY_REQUEST}"
    labels:
      com.octoperf/taskId: "${KRAKEN_TASK_ID}"
      com.octoperf/taskType: "${KRAKEN_TASK_TYPE}"
      com.octoperf/containerName: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_CONTAINER_NAME}"
      com.octoperf/hostId: "${KRAKEN_HOST_ID}"
      com.octoperf/label: "${KRAKEN_GATLING_CONTAINER_LABEL}"
      com.octoperf/description: "${KRAKEN_DESCRIPTION}"
      com.octoperf/expectedCount: "${KRAKEN_EXPECTED_COUNT}"
      com.octoperf/applicationId: "${KRAKEN_APPLICATION_ID}"
      com.octoperf/projectId: "${KRAKEN_PROJECT_ID}"
      com.octoperf/userId: "${KRAKEN_USER_ID}"
    environment:
      KRAKEN_CONTAINER_TASKID: "${KRAKEN_TASK_ID}"
      KRAKEN_CONTAINER_TASKTYPE: "${KRAKEN_TASK_TYPE}"
      KRAKEN_CONTAINER_NAME: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_CONTAINER_NAME}"
      KRAKEN_CONTAINER_HOSTID: "${KRAKEN_HOST_ID}"
      KRAKEN_CONTAINER_USERID: "${KRAKEN_USER_ID}"
      KRAKEN_CONTAINER_PROJECTID: "${KRAKEN_PROJECT_ID}"
      KRAKEN_CONTAINER_APPLICATIONID: "${KRAKEN_APPLICATION_ID}"
      KRAKEN_GATLING_SIMULATION_NAME: "${KRAKEN_GATLING_SIMULATION_NAME}"
      KRAKEN_GATLING_DESCRIPTION: "${KRAKEN_DESCRIPTION}"
      KRAKEN_GATLING_JAVAOPTS: "${KRAKEN_GATLING_JAVA_OPTS} -Xmx${KRAKEN_GATLING_XMX}"
      KRAKEN_BACKEND_URL: "${KRAKEN_BACKEND_URL}"
      JAVA_OPTS: "-Dspring.profiles.active=docker -Xmx${KRAKEN_GATLING_XMX}"
      KRAKEN_SECURITY_URL: "${KRAKEN_SECURITY_URL}"
      KRAKEN_SECURITY_WEB_ID: "${KRAKEN_SECURITY_WEB_ID}"
      KRAKEN_SECURITY_CONTAINER_ID: "${KRAKEN_SECURITY_CONTAINER_ID}"
      KRAKEN_SECURITY_CONTAINER_SECRET: "${KRAKEN_SECURITY_CONTAINER_SECRET}"
      KRAKEN_SECURITY_REALM: "${KRAKEN_SECURITY_REALM}"
      KRAKEN_SECURITY_ACCESSTOKEN: "${KRAKEN_SECURITY_ACCESS_TOKEN}"
      KRAKEN_SECURITY_REFRESHTOKEN: "${KRAKEN_SECURITY_REFRESH_TOKEN}"
      KRAKEN_SECURITY_EXPIRESIN: "${KRAKEN_SECURITY_EXPIRES_IN}"
      KRAKEN_SECURITY_REFRESHEXPIRESIN: "${KRAKEN_SECURITY_REFRESH_EXPIRES_IN}"
      KRAKEN_GATLING_SCENARIO_CUSTOM_SETUP: "${KRAKEN_GATLING_SCENARIO_CUSTOM_SETUP}"
    volumes:
      - type: volume
        source: gatling-volume
        target: /kraken/gatling/results
    extra_hosts:
      - "${KRAKEN_HOSTNAME}:${KRAKEN_IP}"

  kraken-gatling-log-parser:
    image: "octoperf/kraken-gatling-log-parser:${KRAKEN_VERSION}"
    container_name: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_SIDEKICK_NAME}_STARTING"
    networks:
      - kraken
    deploy:
      resources:
        limits:
          cpus: "${KRAKEN_SIDEKICK_CPU_LIMIT}"
          memory: "${KRAKEN_SIDEKICK_MEMORY_LIMIT}"
        reservations:
          cpus: "${KRAKEN_SIDEKICK_CPU_REQUEST}"
          memory: "${KRAKEN_SIDEKICK_MEMORY_REQUEST}"
    labels:
      com.octoperf/taskId: "${KRAKEN_TASK_ID}"
      com.octoperf/taskType: "${KRAKEN_TASK_TYPE}"
      com.octoperf/containerName: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_SIDEKICK_NAME}"
      com.octoperf/hostId: "${KRAKEN_HOST_ID}"
      com.octoperf/label: "${KRAKEN_GATLING_SIDEKICK_LABEL}"
      com.octoperf/description: "${KRAKEN_DESCRIPTION}"
      com.octoperf/expectedCount: "${KRAKEN_EXPECTED_COUNT}"
      com.octoperf/applicationId: "${KRAKEN_APPLICATION_ID}"
      com.octoperf/projectId: "${KRAKEN_PROJECT_ID}"
      com.octoperf/userId: "${KRAKEN_USER_ID}"
    environment:
      KRAKEN_CONTAINER_TASKID: "${KRAKEN_TASK_ID}"
      KRAKEN_CONTAINER_TASKTYPE: "${KRAKEN_TASK_TYPE}"
      KRAKEN_CONTAINER_NAME: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_SIDEKICK_NAME}"
      KRAKEN_CONTAINER_HOSTID: "${KRAKEN_HOST_ID}"
      KRAKEN_CONTAINER_USERID: "${KRAKEN_USER_ID}"
      KRAKEN_CONTAINER_PROJECTID: "${KRAKEN_PROJECT_ID}"
      KRAKEN_CONTAINER_APPLICATIONID: "${KRAKEN_APPLICATION_ID}"
      KRAKEN_BACKEND_URL: "${KRAKEN_BACKEND_URL}"
      JAVA_OPTS: "-Dspring.profiles.active=docker -Xmx${KRAKEN_SIDEKICK_XMX}"
      KRAKEN_SECURITY_URL: "${KRAKEN_SECURITY_URL}"
      KRAKEN_SECURITY_WEB_ID: "${KRAKEN_SECURITY_WEB_ID}"
      KRAKEN_SECURITY_CONTAINER_ID: "${KRAKEN_SECURITY_CONTAINER_ID}"
      KRAKEN_SECURITY_CONTAINER_SECRET: "${KRAKEN_SECURITY_CONTAINER_SECRET}"
      KRAKEN_SECURITY_REALM: "${KRAKEN_SECURITY_REALM}"
      KRAKEN_SECURITY_ACCESSTOKEN: "${KRAKEN_SECURITY_ACCESS_TOKEN}"
      KRAKEN_SECURITY_REFRESHTOKEN: "${KRAKEN_SECURITY_REFRESH_TOKEN}"
      KRAKEN_SECURITY_EXPIRESIN: "${KRAKEN_SECURITY_EXPIRES_IN}"
      KRAKEN_SECURITY_REFRESHEXPIRESIN: "${KRAKEN_SECURITY_REFRESH_EXPIRES_IN}"
    volumes:
      - type: volume
        source: gatling-volume
        target: /kraken/gatling/results
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - kraken-gatling-debugger
    extra_hosts:
      - "${KRAKEN_HOSTNAME}:${KRAKEN_IP}"

volumes:
  gatling-volume:
    name: ${KRAKEN_TASK_ID}-gatling-volume