{
 "title": "Gatling Report",
 "time": { "from": "2019-09-24T09:01:35.099Z", "to": "2019-09-24T09:02:25.169Z" },
 "templating": {
  "list": [
   {
    "name": "request",
    "query": "SHOW TAG VALUES ON \"gatling\" WITH KEY = \"request\" WHERE  \"test\" =~ /^$test$/ AND \"request\" != 'allRequests' AND \"status\" = 'all'"
   },
   {
    "name": "test",
    "query": "44fe487f-215e-46d1-a921-1370fd20ef8e"
   },
   {
    "name": "injector",
    "query": "SHOW TAG VALUES ON \"gatling\" WITH KEY = \"injector\" WHERE  \"test\" =~ /^$test$/"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allUsers" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Hits Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors Percentage",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "all",
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE (\"status\" = 'ko') AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "ko",
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE (\"status\" = 'ko') AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "User Load per Profile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_request on $tag_injector",
     "groupBy": [
      { "params": [ "request" ], "type": "tag" },
      { "params": [ "injector" ], "type": "tag" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "!=", "value": "allUsers" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Response Times Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Minimum" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Maximum" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Percentiles Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Percentiles 99" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Percentiles 95" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Percentiles 75" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Percentiles 50" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times Per Injector (Percentile 95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "$tag_injector",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "injector" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Mean Response Times / request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"max\" FROM \"gatling\" WHERE (\"request\" != 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "!=", "value": "allRequests" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Percentile 95 Response Times / request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"max\" FROM \"gatling\" WHERE (\"request\" != 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "!=", "value": "allRequests" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  { "title": "Requests Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "All Requests Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 42 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE (\"status\" != 'all') AND $timeFilter GROUP BY \"status\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "!=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "all" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests Status Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "ok" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "request", "operator": "!=", "value": "allRequests" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "ko" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "request", "operator": "!=", "value": "allRequests" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests status over time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE (\"status\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "KO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  { "title": "Filtered Request: $request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Request Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") FROM \"gatling\" WHERE (\"status\" != 'all') AND $timeFilter GROUP BY \"status\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "all" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Status Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "KO",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT mean(\"count\") FROM \"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"status\" != 'ko' AND \"test\" =~ /^$test$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Percentile 95" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  { "title": "Injector: $injector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 66 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "injector", "operator": "=~", "value": "/^$injector$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "IO Wait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "injector", "operator": "=~", "value": "/^$injector$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load 1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load 5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load 15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "injector", "operator": "=~", "value": "/^$injector$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 72 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "mem",
     "query": "SELECT last(\"total\") FROM \"mem\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "injector", "operator": "=~", "value": "/^$injector$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "injector", "operator": "=~", "value": "/^$injector$/" }
     ]
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "swap_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Swap Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "injector", "operator": "=~", "value": "/^$injector$/" }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Sent" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Received" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "injector", "operator": "=~", "value": "/^$injector$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "injector", "operator": "=~", "value": "/^$injector$/" }
     ]
    }
   ]
  }
 ]
}